
theme = "onedark"

[editor]
line-number = "relative"
mouse = false
bufferline = "multiple"
cursorline = true

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.indent-guides]
render = true

[editor.lsp]
display-inlay-hints = true

[keys.normal]
C-s = ":w"
esc = ["collapse_selection", "keep_primary_selection"]

